[program:sub2api]
command=/usr/local/bin/sub2api
directory=/Users/lzw/code/my/go/sub2api
user=lzw
autostart=true
autorestart=true
environment=DATA_DIR="/Users/lzw/code/my/go/sub2api/data",RUN_MODE="standard",TZ="Asia/Shanghai",HTTP_PROXY="http://127.0.0.1:6152",HTTPS_PROXY="http://127.0.0.1:6152",ALL_PROXY="http://127.0.0.1:6152",http_proxy="http://127.0.0.1:6152",https_proxy="http://127.0.0.1:6152",all_proxy="http://127.0.0.1:6152",NO_PROXY="127.0.0.1,localhost",no_proxy="127.0.0.1,localhost"
redirect_stderr=false
priority=12
stdout_logfile=/Users/lzw/log/supervisor/sub2api/out.log
stderr_logfile=/Users/lzw/log/supervisor/sub2api/err.log
